# Website settings
url: "https://donfung.github.io/"
baseurl: ""

# Internal nav
nav:
  main:
    projects: "/projects"
    dbf_2019: "dbf_2019"

# Bio settings
name: "Catie Vitella"
description: "The home page of Catie Vitella."
thumbnail_path: "profile-photos/catievitella_profile.jpg"

# URLs
contact_urls:
  linkedin:
    url: "www.linkedin.com/in/catie-vitella"
    label: "LinkedIn"
    icon: "linkedin-square"
  email:
    url: "mailto:catie.vitella@gmail.com"
    label: "Email"
    value: "catie.vitella@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
markdown: kramdown

disqus:
  shortname: catievitella

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
